### ISSUE TITLE
android apk package request

### ISSUE THREAD

**Issue by shuwai** [Ericwyn/seanote#3]
你好, 我是从[这里](https://bbs.seafile.com/t/seafile-app/4142)找到这个项目的. 首先非常感谢你的奉献精神, 以及敬佩你说做就做的决心和能力.

我是从近期开始使用seafile, 我一直在寻找能在手机上编辑云端md文件的方法. 正好我找到了你的这个项目, 尽管该repo似乎不再活跃, 但这是我目前能找到最合适的方案了. (官方一直没有发布类似客户端)

但你的项目并没有releases, 请问是否可以提供apk安装包? 十分感谢!

**Comment by Ericwyn** [comment]
你好啊~这个项目起初是因为我希望基于 Seafile 做一款云笔记应用，但是具体的操作当中发现有些问题比较难以解决，例如笔记的同步策略（冲突的时候如何解决），以及 markdown 编辑器的可用性等，再加上我对 Android 开发并不太熟悉，所以项目便停滞了。项目当前仅仅具有基础的样子而已，并没法实现完整的功能，所以并没有 release 以及打包

**Comment by Ericwyn** [comment]
> 你好, 我是从[这里](https://bbs.seafile.com/t/seafile-app/4142)找到这个项目的. 首先非常感谢你的奉献精神, 以及敬佩你说做就做的决心和能力.
> 
> 我是从近期开始使用seafile, 我一直在寻找能在手机上编辑云端md文件的方法. 正好我找到了你的这个项目, 尽管该repo似乎不再活跃, 但这是我目前能找到最合适的方案了. (官方一直没有发布类似客户端)
> 
> 但你的项目并没有releases, 请问是否可以提供apk安装包? 十分感谢!

不过目前官方的 web 客户端以及 seafile Android 客户端都已经提供了比较良好的 markdown 编辑功能，你可以尝试一下噢~
